meta: fix the cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
 Loaded 617 security advisories (from /builds/vincenzopalazzo/validating-lightning-signer/.cache/cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (312 crate dependencies)
error: 1 vulnerability found!
Crate:     h2
Version:   0.3.24
Title:     Degradation of service in h2 servers with CONTINUATION Flood
Date:      2024-04-03
ID:        RUSTSEC-2024-0332
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0332
Solution:  Upgrade to ^0.3.26 OR >=0.4.4
Dependency tree:

Changelog-None: meta: fix the cargo audit
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>